/**
 * Telegram data loader - reads from cached JSON file
 * The JSON file is generated by scripts/fetch-telegram.py
 */

import { promises as fs } from 'fs';
import path from 'path';

export interface TelegramPost {
  id: string;
  title: string;
  content: string[];
  date: string;
  timestamp: string;
  link: string;
  image?: string;
  mediaType?: 'photo' | 'video' | null;
  hasMedia: boolean;
}

interface TelegramCache {
  updated: string;
  channel: string;
  posts: TelegramPost[];
}

const CACHE_FILE = path.join(process.cwd(), 'public', 'telegram-posts.json');

export async function getCachedTelegramPosts(limit: number = 5): Promise<TelegramPost[]> {
  try {
    // Read the cached JSON file
    const fileContent = await fs.readFile(CACHE_FILE, 'utf-8');
    const data: TelegramCache = JSON.parse(fileContent);

    console.log(`[Telegram] Loaded ${data.posts.length} posts from cache (updated: ${data.updated})`);

    return data.posts.slice(0, limit);
  } catch (error) {
    console.error('[Telegram] Error reading cache file:', error);
    console.log('[Telegram] Run "python scripts/fetch-telegram.py" to generate cache');

    // Return empty array if cache doesn't exist
    return [];
  }
}

export async function getCacheAge(): Promise<number | null> {
  try {
    const fileContent = await fs.readFile(CACHE_FILE, 'utf-8');
    const data: TelegramCache = JSON.parse(fileContent);
    const updated = new Date(data.updated);
    const now = new Date();
    return now.getTime() - updated.getTime(); // milliseconds
  } catch {
    return null;
  }
}
